# Generated by Django 4.2.18 on 2025-01-17 13:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('StudentOrStaff', models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff')], default='Student', max_length=100)),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=30)),
                ('country', models.CharField(default='', max_length=30)),
                ('image', models.ImageField(default='media/profile_pics/default.jpeg', upload_to='media/profile_pics')),
            ],
        ),
    ]
