# Generated by Django 4.2.18 on 2025-01-18 07:38

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('name', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('Course_Code', models.CharField(default='0000', max_length=10)),
                ('credits', models.IntegerField(default=0)),
                ('category', models.BooleanField(choices=[('compulsary', 'compulsary'), ('voluntary', 'voluntary')], default='voluntary')),
                ('Description', models.TextField(default='', max_length=200)),
                ('Course', models.CharField(default='', max_length=50)),
                ('avalaible', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True, null=True)),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.module')),
                ('user', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(default='', max_length=40, primary_key=True, serialize=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.module')),
            ],
        ),
    ]
