# Generated by Django 4.2.18 on 2025-01-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
