# Generated by Django 4.2.18 on 2025-01-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_module_course_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='avalaible',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='module',
            name='category',
            field=models.CharField(choices=[('compulsary', 'compulsary'), ('voluntary', 'voluntary')], max_length=10),
        ),
    ]
