# Generated by Django 4.2.18 on 2025-01-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_course_name_module_coursename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='course_name',
            new_name='coursename',
        ),
    ]
