# Generated by Django 4.2.18 on 2025-01-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todaysDate', models.DateField(auto_now_add=True)),
                ('name', models.CharField(default='N/A', max_length=20)),
                ('email', models.EmailField(default='', max_length=20)),
                ('subject', models.CharField(default='', max_length=50)),
                ('message', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='issue',
            name='description',
        ),
        migrations.AlterField(
            model_name='issue',
            name='details',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='issue',
            name='room',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software')], max_length=10),
        ),
    ]
